stages:
  - stage: DeployUat
    variables:
         - group: 'YAML-Release-UAT'
    jobs:
      - deployment:
        pool:
          vmImage: "windows-latest"
          name: Azure Pipelines
        environment: 'Uat'
        strategy:
         runOnce:
           deploy:
             steps:
               - task: AzureCLI@1
                 inputs:
                   azureSubscription: 'SPNSubscription611a4'
                   scriptLocation: 'inlineScript'
                   inlineScript: |
                      call az group create --location southindia --name $(terraformstoragerg)
     
                      call az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location southindia --sku Standard_LRS
                      
                      call az storage container create --name terraform --account-name  $(terraformstorageaccount) 
                      
                      call az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount) 


           
               - task: AzurePowerShell@3
                 inputs:
                   azureSubscription: 'SPNSubscription611a4'
                   ScriptType: 'InlineScript'
                   Inline: |
                     $key=(Get-AzureRmStorageAccountKey -ResourceGroupName $(terraformstoragerg) -AccountName $(terraformstorageaccount)).Value[0]
                                          
                     Write-Host "##vso[task.setvariable variable=storagekey]$key"
                   azurePowerShellVersion: 'LatestVersion'
                  
               - task: replacetokens@3
                 inputs:
                   rootDirectory: 'D:\a\1\drop\terraform'
                   targetFiles: 'terraform.tf'
                   escapeType: none
                   tokenPrefix: '__'
                   tokenSuffix: '__'

               

               - task: TerraformInstaller@0
                 inputs:
                   terraformVersion: '0.12.3'
              
               - task: TerraformTaskV1@0
                 displayName: 'Terraform : azurerm'
                 inputs:
                    workingDirectory: 'D:\a\1\drop\terraform'
                    backendServiceArm: SPNSubscription611a4
                    backendAzureRmResourceGroupName: '$(terraformstoragerg)'
                    backendAzureRmStorageAccountName: '$(terraformstorageaccount) '
                    backendAzureRmContainerName: terraform
                    backendAzureRmKey: terraform.tfstate

                  
               - task: TerraformTaskV2@2
                 inputs:
                   provider: 'azurerm'
                   command: 'plan'
                   workingDirectory: 'D:\a\1\drop\terraform'
                   environmentServiceNameAzureRM: 'SPNSubscription611a4'
                  
               - task: TerraformTaskV2@2
                 inputs:
                   provider: 'azurerm'
                   command: 'apply'
                   workingDirectory: 'D:\a\1\drop\terraform'
                   commandOptions: '-auto-approve'
                   environmentServiceNameAzureRM: 'SPNSubscription611a4'
                  
               - task: AzureRmWebAppDeployment@4
                 inputs:
                   ConnectionType: 'AzureRM'
                   azureSubscription: 'SPNSubscription611a4'
                   appType: 'webApp'
                   WebAppName: '$(appservicename)'
                   packageForLinux: 'D:\a\1\drop\springboot-backend\target'

