resources:
    repositories:
        - repository: Azure-Template
          type: git
          name: PremierBank/Azure-Template
          ref: main

stages:
    - template: Azure_Main_Template.yml@Azure-Template
      parameters:
         ApplicationType: 'docker'  # .Net,Node
         Deploy: 'docker-deploy' #Java_Terraform , Java-App-Service


# stages:
#   - stage: Build
#     jobs:
#       - job: BuildWebApp
#         pool:
#           vmImage: "ubuntu-18.04"
#           name: Azure Pipelines

#         steps:
#         - task: DockerCompose@0
#           displayName: 'Build services'
#           inputs:
#             azureSubscription: SPNSubscription20e84
#             azureContainerRegistry: '{"loginServer":"premieracr203.azurecr.io", "id" : "/subscriptions/fb5eefd5-9b03-48bd-a8c6-47ea6f020e84/resourceGroups/premier_aks_rg/providers/Microsoft.ContainerRegistry/registries/premieracr203"}'
#             dockerComposeFile: 'docker-compose.yml'
#             dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
#             action: 'Build services'
#             additionalImageTags: '$(Build.BuildId)'
#             includeLatestTag: true

#         - task: DockerCompose@0
#           displayName: 'Push services'
#           inputs:
#             azureSubscription: SPNSubscription20e84
#             azureContainerRegistry: '{"loginServer":"premieracr203.azurecr.io", "id" : "/subscriptions/fb5eefd5-9b03-48bd-a8c6-47ea6f020e84/resourceGroups/premier_aks_rg/providers/Microsoft.ContainerRegistry/registries/premieracr203"}'
#             dockerComposeFile: 'docker-compose.yml'
#             dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
#             action: 'Push services'
#             additionalImageTags: '$(Build.BuildId)'
#             includeLatestTag: true

#         - task: CopyFiles@2
#           displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
#           inputs:
#             Contents: '**/premier-aks.yaml'
#             TargetFolder: '$(Build.ArtifactStagingDirectory)'

#         - task: PublishBuildArtifacts@1
#           displayName: 'Publish Artifact: drop'


#   - stage: Deploy
#     jobs:
#       - deployment: 
#         pool:
#           vmImage: "ubuntu-18.04"
#           name: Azure Pipelines
#         environment: 'Dev'
#         strategy:
#          runOnce:
#            deploy:
#              steps:
              
#              - task: Kubernetes@1
#                displayName: 'kubectl apply'
#                inputs:
#                  connectionType: 'Azure Resource Manager'
#                  azureSubscriptionEndpoint: SPNSubscription20e84
#                  azureResourceGroup: 'premier_aks_rg'
#                  kubernetesCluster: 'premier-akscluster'
#                  command: apply
#                  useConfigurationFile: true
#                  configuration: '/home/vsts/work/1/drop/premier-aks.yaml'
#                  checkLatest: true