version: '3'

#Define services
services:

#   #PostgreSQL Database for the application
#   scrum-postgres:
#     image: "postgres:9.6-alpine"
#     container_name: scrum-postgres
#     #Volume mounted for database for the storage
#     volumes:
#       - scrum-data:/var/lib/postgresql/data
#     ports:
#       - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

#     #Environment variable for DB name, user and password
#     environment:
#       - POSTGRES_DB=scrum
#       - POSTGRES_USER=scrum
#       - POSTGRES_PASSWORD=scrum

  #Back-end Spring Boot Application
  springboot-backend:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./springboot-backend
    container_name: springboot-backend

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=mysqlserver-backend.mysql.database.azure.com
      - POSTGRES_DB=primeBank
      - POSTGRES_USER=Admin123@mysqlserver-backend
      - POSTGRES_PASSWORD=admin@123
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    # links:
    #   - scrum-postgres

  #Fron-end Angular Application
  angular-frontend:
    build: ./angular-frontend
    container_name: angular-frontend
    ports:
      - 4200:80
    links:
      - springboot-backend

#Volumes for DB data
# volumes:
#   scrum-data: