resources:
  repositories:
    - repository: Azure-Template
      type: git
      name: PremierBankPOC/Azure-Template
      ref: main

trigger:
  branches:
    include:
    - main



stages:
- template: Azure_Main_Template.yml@Azure-Template
  parameters:
       ApplicationType: 'node'
       BuildTool: 'Npm'
       Deploy: 'Azure-App-Service'
       Test: 'Owasp'
        