resources:
  repositories:
    - repository: Azure-Template
      type: git
      name: PremierBank/Azure-Template
      ref: main



stages:
#  - stage: "Dev"
#    jobs:
   - template: Azure_Main_Template.yml@Azure-Template
     parameters:
       ApplicationType: 'node'
       BuildTool: 'Npm'
       CodeAnalysis: 'Sonarqube' 
       Deploy: 'Azure-App-Service'
       path: 'D:\a\1\drop\angular-frontend'
       SecurityTest: 'Owasp'
  
#  - stage: "Uat"
#    jobs:
#    - template: Azure_Main_Template.yml@Azure-Template
#      parameters:
      #  ApplicationType: 'node'
      #  BuildTool: 'Npm'
      #  CodeAnalysis: 'Sonarqube' 
      #  Deploy: 'Terraform'
      #  path: 'D:\a\1\drop\angular-frontend'
      #  SecurityTest: 'Owasp'
      #  hello world