resources:
  repositories:
    - repository: Azure-Template
      type: git
      name: PremierBank/Azure-Template
      ref: main



stages:
   - template: Azure_Main_Template.yml@Azure-Template
     parameters:
       ApplicationType: 'node'
       BuildTool: 'Npm'
       workingDir: 'angular-frontend'
       CodeAnalysis: 'Sonarqube' 
       Deploy: 'Azure-App-Service'
       path: 'D:\a\1\drop\angular-frontend'
      #  SecurityTest: 'Owasp'
  
