resources:
  repositories:
    - repository: Azure-Template
      type: git
      name: PremierBank/Azure-Template
      ref: main



stages:
  - template: Azure_Main_Template.yml@Azure-Template
    parameters:
       ApplicationType: 'node'
       BuildTool: 'Npm'
       Version: '6.0'
       workingDir: 'angular-frontend'
       BuildCommand: 'run build-prod'
       CodeAnalysis: 'Sonarqube' 
       Deploy: 'Terraform'
       path: 'D:\a\1\drop\angular-frontend'
       #  SecurityTest: 'Owasp'
       # Owasp_url: 'https://webapp-backend01.azurewebsites.net/'
      
