# parameters:
#   Version: 1.8
#   BuildTool: 'Maven'
  

stages:
  - stage: Build
    jobs:
      - job: BuildWebApp
        pool:
          vmImage: "windows-latest"
          name: Azure Pipelines
          demands: maven

        steps:
        - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
          displayName: 'Prepare analysis on SonarQube'
          inputs:
            SonarQube: PremierBankPOC
            scannerMode: Other

        - task: Maven@3
          displayName: 'Maven springboot-backend/pom.xml'
          inputs:
            mavenPomFile: 'springboot-backend/pom.xml'
            goals: 'package clean clean verify sonar:sonar '
            testRunTitle: TestCases
            codeCoverageToolOption: JaCoCo
            sonarQubeRunAnalysis: true
            isJacocoCoverageReportXML: true

        - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
          displayName: 'Publish Quality Gate Result'

        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
          inputs:
            SourceFolder: '$(system.defaultworkingdirectory)'
            Contents: '**/*.jar'
            TargetFolder: '$(build.artifactstagingdirectory)'
          condition: succeededOrFailed()



        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)/OWASP'
          inputs:
            SourceFolder: 'springboot-backend/OWASP'
            TargetFolder: '$(build.artifactstagingdirectory)/OWASP'

        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)/terraform'
          inputs:
            SourceFolder: 'springboot-backend/terraform'
            TargetFolder: '$(build.artifactstagingdirectory)/terraform'

        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)/ARMTemplate'
          inputs:
            SourceFolder: 'springboot-backend/AZURETEMPLATE'
            TargetFolder: '$(build.artifactstagingdirectory)/ARMTemplate'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
          condition: succeededOrFailed()


  - stage: DeployUat
    jobs:
      - deployment: 
        pool:
          vmImage: "windows-latest"
          name: Azure Pipelines
        environment: 'Uat'
        strategy:
         runOnce:
           deploy:
             steps:
              - task: AzureRmWebAppDeployment@4
                inputs:
                  azureSubscription: SPNMastekLabse3097
                  WebAppName: 'webapp-backend01-Uat'
                  # deployToSlotOrASE: true
                  ResourceGroupName: 'Premier_Bank_UAT'
                  # SlotName: slot
                  packageForLinux: 'D:\a\1\drop\springboot-backend\target\springboot-backend-0.0.1-SNAPSHOT.jar'
                  # packageForLinux: '${{parameters.path}}'
