resources:
  repositories:
    - repository: Azure-Template
      type: git
      name: PremierBank/Azure-Template
      ref: main
 
trigger:
  branches:
    include:
    - main
 
stages:
- template: Azure_Main_Template.yml@Azure-Template
  parameters:
       ApplicationType: 'java'
       Version: 1.8
       BuildTool: 'Maven'
       CodeCoverage: 'Sonarqube'
       Deploy: 'Java_Terraform' #Java_Terraform , Java-App-Service
       SecurityTest: 'Owasp' #we can use 
       FunctionalTest: 'UFT' #we can use TricentisTosca,SauceLabs
       IntegrationTest: 'DBUnit'#we can use Greenmail,JMockit1
       JUnitTest: 'JMockit'#we can use  NUnit, Emma