resources:
  repositories:
    - repository: Azure-Template
      type: git
      name: Primer_Bank_demo/Azure-Template
      ref: main

trigger:
  branches:
    include:
    - main

stages:
- template: Azure_Main_Template.yml@Azure-Template
  parameters:
       ApplicationType: 'java'
       BuildTool: 'Maven'
       CodeAnalysis: 'Sonarqube' 
       Deploy: 'Java-App-Service'
       Test: 'Owasp'
        
 