resources:
    repositories:
        - repository: Azure-Template
          type: git
          name: PremierBank/Azure-Template
          ref: main

stages:
    - template: Azure_Main_Template.yml@Azure-Template
      parameters:
         ApplicationType: 'cosmosdb'  # .Net,Node
         Deploy: 'cosmos-infra-provision'
